apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 8 }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
